### PR TITLE
Serialized collectives

### LINKED ISSUE #11: [BUG] Threaded_blocksparse incompatible with MPI when using DMRG with QNs
If one tries to activate `threaded_blocksparse` and `MPI` parallelization together to perform DMRG calculation using number conserving sites (doesn't matter the SiteType) the following error is returned during the exact diagonalization step (in this particular case the code ran was this [example](https://github.com/ITensor/ITensorParallel.jl/blob/main/examples/05_mpi_threaded_mpo_sum_2d_heisenberg.jl))

```
ERROR: LoadError: BoundsError: attempt to access 4-element Vector{Pair{QN, Int64}} at index [5]
Stacktrace:
  [1] getindex
    @ ./array.jl:861 [inlined]
  [2] getindex
    @ ./abstractarray.jl:1221 [inlined]
  [3] blockdim
    @ ~/.julia/packages/ITensors/5dcHw/src/qn/qnindex.jl:15 [inlined]
  [4] blockdim
    @ ~/.julia/packages/ITensors/5dcHw/src/qn/qnindex.jl:256 [inlined]
  [5] blockdim
    @ ~/.julia/packages/ITensors/5dcHw/src/qn/qnindex.jl:273 [inlined]
  [6] blockdim
    @ ~/.julia/packages/NDTensors/lbVmG/src/blocksparse/blockdims.jl:131 [inlined]
  [7] #124
    @ ~/.julia/packages/NDTensors/lbVmG/src/blocksparse/blockdims.jl:140 [inlined]
  [8] macro expansion
    @ ./ntuple.jl:74 [inlined]
  [9] ntuple
    @ ./ntuple.jl:69 [inlined]
 [10] blockdims
    @ ~/.julia/packages/NDTensors/lbVmG/src/blocksparse/blockdims.jl:140 [inlined]
 [11] blockdim
    @ ~/.julia/packages/NDTensors/lbVmG/src/blocksparse/blockdims.jl:149 [inlined]
 [12] blockoffsets(blocks::Vector{Block{4}}, inds::NTuple{4, Index{Vector{Pair{QN, Int64}}}})
    @ NDTensors ~/.julia/packages/NDTensors/lbVmG/src/blocksparse/blockoffsets.jl:71
 [13] (NDTensors.BlockSparseTensor)(#unused#::Type{Float64}, blocks::Vector{Block{4}}, inds::NTuple{4, Index{Vector{Pair{QN, Int64}}}})
    @ NDTensors ~/.julia/packages/NDTensors/lbVmG/src/blocksparse/blocksparsetensor.jl:97
 [14] _Allreduce(#unused#::Type{NDTensors.BlockSparse{Float64, Vector{Float64}, 4}}, sendbuf::ITensor, op::Function, comm::MPI.Comm)
    @ ITensorParallel ~/.julia/packages/ITensorParallel/63YWQ/src/mpi_projmposum.jl:44
 [15] _Allreduce(sendbuf::ITensor, op::Function, comm::MPI.Comm)
    @ ITensorParallel ~/.julia/packages/ITensorParallel/63YWQ/src/mpi_projmposum.jl:22
 [16] eigsolve(A::MPISum{ProjMPO}, x₀::ITensor, howmany::Int64, which::Symbol, alg::KrylovKit.Lanczos{KrylovKit.ModifiedGramSchmidt2, Float64})
    @ KrylovKit ~/.julia/packages/KrylovKit/kWdb6/src/eigsolve/lanczos.jl:11
```

It looks like the error slightly changes by changing the dimension of the MPS. In the previous example I used a 8x2 lattice while if I use a 4x2 lattice I get

```
ERROR: LoadError: MPIError(15): MPI_ERR_TRUNCATE: message truncated
Stacktrace:
 [1] MPI_Allreduce
   @ ~/.julia/packages/MPI/tJjHF/src/api/generated_api.jl:288 [inlined]
 [2] Allreduce!(rbuf::MPI.RBuffer{Vector{Float64}, Vector{Float64}}, op::MPI.Op, comm::MPI.Comm)
   @ MPI ~/.julia/packages/MPI/tJjHF/src/collective.jl:653
 [3] _Allreduce(sendbuf::ITensor, op::Function, comm::MPI.Comm)
   @ ITensorParallel ~/.julia/packages/ITensorParallel/63YWQ/src/mpi_projmposum.jl:22
 [4] eigsolve(A::MPISum{ProjMPO}, x₀::ITensor, howmany::Int64, which::Symbol, alg::KrylovKit.Lanczos{KrylovKit.ModifiedGramSchmidt2, Float64})
   @ KrylovKit ~/.julia/packages/KrylovKit/kWdb6/src/eigsolve/lanczos.jl:11
in expression starting at /mnt/home/nbaldelli/parheis.jl:61
```

`threaded_blocksparse` and `MPI` work smoothly singularly by deactivating the other and work together by turning off the QNs conservation. 

I ran the code using `mpirun` by using the following bash script:

```
#!/bin/bash
#SBATCH -N2
#SBATCH --ntasks-per-node 1 
#SBATCH --cpus-per-task 8

module purge
module load slurm
module load openmpi/4
module load julia
julia --project -e 'ENV["JULIA_MPI_BINARY"]="system"; using Pkg; Pkg.build("MPI"; verbose=true)'
mpirun julia -t 8 <name_file_here>
```

### PR DESCRIPTION
**Pull request by b-kloss**
This implements a serialized MPI collective routine `_gather` to be used in MPISum reduction across nodes via `_allreduce`. The prior implementation via `MPI.Allreduce` of the data of an ITensor required same index and block-ordering across nodes, making it failure-prone and is thus removed. Synchronization of linkindices across processes during a DMRG run is taken care of by reimplementation of `position!` for `MPISum`.
Closes #11 .

### CODE REVIEW

File: src/mpi_projmposum.jl [hunk 1]
```diff
@@ -18,44 +18,24 @@ nsite(P::MPISum) = nsite(P.data)
...
-  recvbuf = similar(sendbuf)
-  MPI.Allreduce!(sendbuf, recvbuf, op, comm)
-  return recvbuf
+function _allreduce(sendbuf, op, comm::MPI.Comm)
+  ##maybe better to implement as allgather with local reduce, but higher communication cost associated
+  bufs = _gather(sendbuf, 0, comm)
+  rank = MPI.Comm_rank(comm)
+  if rank == 0
+    if op == +
+      res = sum(bufs)
```
Comment (mtfishman) [inline src/mpi_projmposum.jl:27]: Was there an issue with just using `reduce(op, bufs)` in this case?

File: src/mpi_projmposum.jl [hunk 2]
```diff
@@ -18,44 +18,24 @@ nsite(P::MPISum) = nsite(P.data)
...
-  sendbuf_filled .= sendbuf
-  MPI.Allreduce!(sendbuf_filled, recvbuf, +, comm)
-  return recvbuf
-end
-
-function _Allreduce(::Type{<:Dense}, sendbuf::ITensor, op, comm)
-  recvbuf = similar(sendbuf)
-  MPI.Allreduce!(sendbuf, recvbuf, op, comm)
-  return recvbuf
+function _allreduce(sendbuf, op, comm::MPI.Comm)
```
Comment (mtfishman) [inline src/mpi_projmposum.jl:21]: Should we move this to `mpi_aux.jl`? Also I would just rename to `allreduce`.

File: src/mpi_aux.jl [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+    if !isroot
+        buf = Array{UInt8}(undef, count[])
+    end
+    Bcast!(buf, root, comm)
+    if !isroot
+        obj = MPI.deserialize(buf)
+    end
+    return obj
+end
+"""
```
Comment (mtfishman) [inline src/mpi_aux.jl:22]: I guess this just wasn't tested yet?

File: src/mpi_aux.jl [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+
+_gather(obj, comm::MPI.Comm, root::Integer=Cint(0)) = _gather(obj, root, comm)
+function _gather(obj, root::Integer, comm::MPI.Comm)
```
Comment (mtfishman) [inline src/mpi_aux.jl:25]: I would rename to `_gather`.

File: src/mpi_projmposum.jl (hunk 2 above)
Comment (b-kloss) [reply src/mpi_projmposum.jl:21]: Sure. I used the underscored naming also for `_gather`, to avoid collision with potential future implementations in MPI.jl. Is that bad style (since it's not strictly 'private') ?

File: src/mpi_projmposum.jl (hunk 1 above)
Comment (b-kloss) [reply src/mpi_projmposum.jl:27]: No. I'll remove the if statement.
